### ISSUE TITLE
일정 상세 페이지, n일차 탭 클릭 여러번 할 경우 에러 발생

### ISSUE THREAD

**Issue by reeny404** [0dytpq0/final-project-b1#107]
2일차 클릭 -> 3일차 클릭 -> 4일차 클릭 하면 아래와 같은 화면이 나옵니다. 

![Image](https://github.com/user-attachments/assets/b1854ddb-9e3c-4da5-8633-bce2c325ba4c)

**Comment by LeeJunhyeok369** [comment]
해결했습니다

**Comment by reeny404** [comment]
@LeeJunhyeok369  해결하신 PR 링크나 commit 링크 남겨주세요

**Comment by LeeJunhyeok369** [comment]
https://github.com/0dytpq0/final-project-b1/commit/0b6aa6f8554e0b27677f2209bc15ffe2b16e90f0#diff-7d9952ee0b1fe741c6dbfbb59a58124d54d99ce2c80a8ca51ff72f5e044581f6
