### ISSUE TITLE
스케줄 생성 불가

### ISSUE THREAD

**Issue by reeny404** [0dytpq0/final-project-b1#55]
## 어떤 버그인가요?
- 스케줄 생성 불가

## 어떤 상황에서 발생한 버그인가요?
- https://final-project-b1.vercel.app/plan/create 페이지의 우측 하단 생성 버튼 클릭하면 바텀시트나 나옴
- 바텀시트에서 1) 메모만 입력 2) 메모와 시간 입력 두종류의 insert 테스트 시 error 발생
- 에러메세지 : [22007] null > invalid input syntax for type time: ""

## 예상 결과
- 데이터 DB insert -> API 200대로 정상 응답 -> 바텀 시트 닫힘

## 참고할만한 자료(선택)
![image](https://github.com/user-attachments/assets/502e9722-019d-4e23-a33c-44ed8cf1e5fa)
![image](https://github.com/user-attachments/assets/46d04583-2327-42ae-bea9-275898728d6e)

**Comment by LeeJunhyeok369** [comment]
URL key 변경 해결
